version: "3.9"
services:
  builder:
    container_name: aosp_builder
    hostname: aosp_builder
    build: ./build
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/gitconfig:/home/aosp/.gitconfig:ro
      - ~/aosp:/aosp:rw
      - ~/ccache:/ccache:rw